[aws]
symbol = "a "

[gcloud]
symbol = 'ğŸ‡¬ï¸ '
format = 'on [$symbol$project]($style) '

[kubernetes]
disabled = false
style = "bold blue"

[kubernetes.context_aliases]
"arn:aws:eks.*/(?P<cluster>[\\w-]+)" = "$cluster"

[python]
format = 'via [${symbol}${pyenv_prefix}($virtualenv )]($style)'
